// vim: set syntax=asciidoc:
[[docker_basic_workshop_handson]]
= Docker Basics
:data-uri:
:icons:
:toc:
:toclevels 4:
:numbered:
:Author: Lalatendu Mohanty, Suraj Deshmukh
:Email:  lmohanty@redhat.com surajd@redhat.com

=== Installing Docker

* There are multiple ways to install docker based on your platform, please read the docs https://docs.docker.com/engine/installation/
* You can also get a VM on cloud provider like Amazon or Digital Ocean to make things easier for you.


Fedora
^^^^^^

[source, bash]
-----------------
$ sudo dnf -y install docker
$ sudo systemctl start docker
$ sudo systemctl enable docker
-----------------

For other Linux distributions or Windows , OS X, refer: https://www.docker.com/products/overview

== Installing docker-compose

* We will also look at how to dockerize an existing application and use docker-compose to bring multi-container application. To install docker-compose follow docs here: https://docs.docker.com/compose/install/


== Check your Docker Install

----------
$ docker info
Containers: 2
Images: 13
Server Version: 1.9.1
Storage Driver: devicemapper
 Pool Name: vg001-docker--pool
 Pool Blocksize: 524.3 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: xfs
 Data file: 
 Metadata file: 
 Data Space Used: 798 MB
 Data Space Total: 13.6 GB
 Data Space Available: 12.8 GB
 Metadata Space Used: 225.3 kB
 Metadata Space Total: 46.14 MB
 Metadata Space Available: 45.91 MB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.107-RHEL7 (2015-12-01)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.10.0-327.18.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 2
Total Memory: 992.8 MiB
Name: centos7-adb
ID: PMBW:NKH6:AW3M:PI3A:XLKG:LTJF:O7IE:WGFB:BFEN:G7HS:SDRM:UY5R
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
----------

== Docker Basic operations

=== Search in public docker index
----------
$ docker search fedora
INDEX       NAME                                     DESCRIPTION                                     STARS     OFFICIAL   AUTOMATED
docker.io   docker.io/fedora                         Official Docker builds of Fedora                371       [OK]       
docker.io   docker.io/dockingbay/fedora-rust         Trusted build of Rust programming language...   3                    [OK]
docker.io   docker.io/gluster/gluster-fedora         Official GlusterFS image [ Fedora 21 + Glu...   3                    [OK]
docker.io   docker.io/eminguez/transmission-fedora   Transmission Fedora 22 docker container         2                    [OK]
docker.io   docker.io/startx/fedora                  Simple container used for all startx based...   2                    [OK]
docker.io   docker.io/dasrick/fedora-nginx           NGINX image - port 80, 443 - based on Fedo...   1                    [OK]
docker.io   docker.io/fedora/tools                   Docker image that has systems administrati...   1                    [OK]
docker.io   docker.io/mattsch/fedora-rpmfusion       Base container for Fedora 22 with RPM Fusi...   1                    [OK]
docker.io   docker.io/neroinc/fedora-apache          Plain and simple image with Apache httpd b...   1                    [OK]
docker.io   docker.io/cloudrunnerio/fedora                                                           0                    [OK]
----------

=== Pull an image
----------
$ docker pull fedora
Using default tag: latest
Trying to pull repository docker.io/library/fedora ... latest: Pulling from library/fedora

62b0615068df: Pull complete 
cd1e9127a3f8: Pull complete 
Digest: sha256:52db7a1a18f173622a9b1a75354c7266220bffb7187c4880590805af0d7679d6
Status: Downloaded newer image for docker.io/fedora:latest

$ docker pull alpine
Using default tag: latest
Trying to pull repository docker.io/library/alpine ...
latest: Pulling from docker.io/library/alpine
117f30b7ae3d: Pull complete
Digest: sha256:02eb5cfe4b721495135728ab4aea87418fd4edbfbf83612130a81191f0b2aae3
Status: Downloaded newer image for docker.io/alpine:latest

----------

Try pulling a tagged image i.e. `docker pull fedora:24`

=== Listing images
----------
$ docker images 
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
docker.io/fedora    23                  5a813a9e051e        31 hours ago        214.4 MB
docker.io/fedora    latest              cd1e9127a3f8        34 hours ago        204.4 MB
docker.io/centos    latest              a65193109361        2 weeks ago         196.7 MB
docker.io/ubuntu    latest              8e5b7248472b        3 weeks ago         122 MB
docker.io/busybox   latest              0d380282e68b        3 months ago        1.113 MB

----------
=== Start a container from an image
----------
$ docker run -it fedora bash
[root@57c2ac5812d5 /]# 
[root@57c2ac5812d5 /]# cat /etc/fedora-release 
Fedora release 24 (Twenty Four)

----------
=== Listing the containers

Open another terrminal and run below command while running the container as mentioned in the previous state.

----------
$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
2e18e1d045ed        centos              "bash"              7 minutes ago       Up 7 minutes                            gloomy_spence
5e7d81c7e1ad        busybox             "sh"                7 minutes ago       Up 7 minutes                            kickass_curie

----------
*To list all containers (both running and stopped)*
----------
$ docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS                      PORTS               NAMES
57c2ac5812d5        fedora              "bash"              2 minutes ago       Exited (0) 38 seconds ago                       grave_babbage
2e18e1d045ed        centos              "bash"              7 minutes ago       Up 7 minutes                                    gloomy_spence
5e7d81c7e1ad        busybox             "sh"                7 minutes ago       Up 7 minutes                                    kickass_curie

----------

=== Saving a container state
* Start a container
* Modify a file
----------
$ docker run -i -t fedora /bin/bash
[root@88226d270d64 /]# 
[root@88226d270d64 /]# echo "FUDCon workshop 2015" > /etc/motd

----------

* On a different terminal, save the container as an image
----------
$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
88226d270d64        fedora              "/bin/bash"         41 seconds ago      Up 40 seconds                           small_williams
2e18e1d045ed        centos              "bash"              8 minutes ago       Up 8 minutes                            gloomy_spence
5e7d81c7e1ad        busybox             "sh"                9 minutes ago       Up 9 minutes                            kickass_curie

$ docker commit -a "Lalatendu Mohanty" -m "PyCon 2016" 88226d270d64 pycon:motd
f6b39867b3e9b8f118510a3e956704726291b37984b1abc74ba8b8061f751556


$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
pycon               motd                f6b39867b3e9        5 seconds ago       204.4 MB
docker.io/fedora    23                  5a813a9e051e        31 hours ago        214.4 MB
docker.io/fedora    latest              cd1e9127a3f8        34 hours ago        204.4 MB
docker.io/centos    latest              a65193109361        2 weeks ago         196.7 MB
docker.io/ubuntu    latest              8e5b7248472b        3 weeks ago         122 MB
docker.io/busybox   latest              0d380282e68b        3 months ago        1.113 MB
----------

=== Looking in to Docker metatdata

----------
$ sudo cat /var/lib/docker/repositories-devicemapper  | python -mjson.tool
{
    "ConfirmDefPush": true,
    "Repositories": {
        "docker.io/busybox": {
            "latest": "0d380282e68b755298e8260191124eb84defc04c1de31173df2d837d64e504b8"
        },
        "docker.io/centos": {
            "latest": "a65193109361c1c55a0baa79c2167ec417b977f284b3358f4d50b81e22f84ec5"
        },
        "docker.io/fedora": {
            "23": "5a813a9e051e1d85cb778f9c15ed7e03510958eea9239e0c10a0b22e22fbe8a8",
            "latest": "cd1e9127a3f8fb1619bcb43ff99a3d5113d44aa34035a3cb0f39b883cad53237"
        },
        "docker.io/ubuntu": {
            "latest": "8e5b7248472b1cf370e8b181c357148a5aff33c0b8da2ba133701f599de15a84"
        },
        "pycon": {
            "motd": "f6b39867b3e9b8f118510a3e956704726291b37984b1abc74ba8b8061f751556"
        }
    }
}
----------

=== Attaching to a container

----------
$ ID=$(sudo docker run -d fedora /bin/sh -c "while true; do echo PyCon 2016 ; sleep 1; done")
$ docker attach $ID
PyCon 2016
PyCon 2016
[SNIP]
----------

=== Stop/Start/Restart a conatiner

----------
$ docker stop $ID
$ docker start $ID
$ docker restart $ID
----------

=== Looking at the logs of container
 
----------
$ docker logs $ID
----------

=== Killing a container
 
----------
$ docker stop $ID
$ docker rm $ID
----------

=== Delete all stopped containers
 
----------
$ docker rm `docker ps -a -q`
----------
=== Privileged access inside container
 
----------
$ docker run -t -i fedora /bin/bash
[root@50559bf9ab0a /]# mount -t tmpfs none /mnt 
mount: permission denied
[root@50559bf9ab0a /]# exit
----------

To get privilaged access, please run below command

----------
$ docker run --privileged -t -i fedora /bin/bash
----------

=== Return low level information about container
 
----------
$ docker inspect $ID
$ docker inspect --format='{{.NetworkSettings.IPAddress}}'  $ID
----------
=== Copy files/folders from a PATH on the container to a HOSTDIR on the host
 
----------
$ docker cp $ID:/etc/motd /tmp/
----------

=== Run a command inside a directory while starting a container

----------
$ docker run -t -i -w /etc fedora ls
----------
Note : if the path does not exist, it will get created

=== List the changed files and directories in a container’s filesystem

---------------
docker diff $ID
---------------

* A Add
* D Delete
* C Change

=== History of the image

---------------
$ docker history
---------------

=== Port redirection

*Bind a port to host interface*

* Bind TCP port 8080 of the container to TCP port 80 on 127.0.0.1 of the host machine. 
---------------
$ docker run -d -i -t -p 127.0.0.1:8080:80 fedora bash
---------------

* Bind TCP port 8080 of the container to a dynamically allocated TCP port on 127.0.0.1 of the host machine. 
---------------
$ docker run -d -i -t -p 127.0.0.1::8080 fedora bash
---------------

* Bind TCP port 8080 of the container to TCP port 80 on all available interfaces of the host machine. 
----------------
docker run -d -i -t -p 80:8080 fedora bash
----------------

*  Bind TCP port 8080 of the container to a dynamically allocated TCP port on all available interfaces of the host machine.
---------------
docker run -d -i -t -p 8080 fedora bash
---------------

=== Exposing a port while starting a container

---------------
$ ID=$(docker run --expose=22 -d -i -t pycon:sshd /bin/bash)
---------------

=== Mount a host directory on a conatiner

---------------
$ docker run  -i -t -v /var/logs:/logs_from_host:ro fedora bash
$ ls logs_from_host/
---------------

=== Remove docker image

---------------
docker rmi <imagename>
---------------

Remove all images

---------------
docker rmi $(docker images -q)
---------------

== DockerFiles

=== Building an image

----------
$ mkdir /tmp/pycon; cd /tmp/pycon
$ echo "FROM fedora"  >> Dockerfile
$ echo "MAINTAINER Lalatendu" >> Dockerfile
$ docker build -t pycon/fedora .
$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
pycon/fedora        latest              8ab29ba8abf2        5 seconds ago       204.4 MB
pycon               motd                f6b39867b3e9        18 minutes ago      204.4 MB
docker.io/fedora    23                  5a813a9e051e        31 hours ago        214.4 MB
----------

=== DockerFile Instructions

* FROM <image> | <image>:<tag>

    Set the base image

* MAINTAINER <name>

    Set the author

* RUN <cmd> | ["executable", "param1", "param2"]

    Executes any commands in a new layer on top of the current image and commit the results

* CMD ["executable","param1","param2"] | ["param1","param2"] | command param1 param2

    Provides defaults for an executing container

* EXPOSE <port> [<port> …]

    Open up specified network ports at runtime

* ENV <key> <value>

    This sets the environment variable <key> to the value <value>

* ADD <src> <dest>

    Copy new files from source and add them to the container's filesystem at path

* ENTYRPOINT ["executable", "param1", "param2"] | command param1 param2

    Helps to configure a container that you can run as an executable.

* VOLUME ["/data"]

    Creates a mount point with the specified name and mark it as holding externally mounted volumes from native host or other containers.

* USER

    Sets the username or UID to use when running the image.

* WORKDIR

    Sets the working directory

* ONBUILD [INSTRUCTION]

    Adds to the image a "trigger" instruction to be executed at a later time, when the image is used as the base for another build.


== References

* http://www.slideshare.net/dotCloud/docker-intro-november
* http://www.slideshare.net/jamtur01/introduction-to-docker-30285720
* http://neependra.net/docker/rootconfWorkshop.html
* https://www.packtpub.com/virtualization-and-cloud/docker-cookbook
* https://github.com/LalatenduMohanty/container-workbook
